### ISSUE TITLE
modid PigManure is not the same as it's lowercase version

### ISSUE THREAD

**Issue by kirchner-trevor** [airbreather/pig-manure-mod#6]
**Issues**
When starting a server with PigManure installed the following WARNING and ERROR are displayed.

`[16:24:22] [Server thread/WARN] [FML]: ****************************************
[16:24:22] [Server thread/WARN] [FML]: * The modid PigManure is not the same as it's lowercase version. Lowercasing is enforced in 1.11
[16:24:22] [Server thread/WARN] [FML]: *  at net.minecraftforge.fml.common.FMLModContainer.sanityCheckModId(FMLModContainer.java:145)
[16:24:22] [Server thread/WARN] [FML]: *  at net.minecraftforge.fml.common.FMLModContainer.<init>(FMLModContainer.java:128)
[16:24:22] [Server thread/WARN] [FML]: *  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[16:24:22] [Server thread/WARN] [FML]: *  at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[16:24:22] [Server thread/WARN] [FML]: *  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[16:24:22] [Server thread/WARN] [FML]: *  at java.lang.reflect.Constructor.newInstance(Unknown Source)...
[16:24:22] [Server thread/WARN] [FML]: ****************************************
[16:24:22] [Server thread/ERROR] [FML]: Unable to construct net.minecraftforge.fml.common.Mod container
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_91]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_91]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_91]
        at net.minecraftforge.fml.common.ModContainerFactory.build(ModContainerFactory.java:86) [ModContainerFactory.class:?]
        at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:105) [JarDiscoverer.class:?]
        at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:49) [ContainerType.class:?]
        at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:78) [ModCandidate.class:?]
        at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:141) [ModDiscoverer.class:?]
        at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:393) [Loader.class:?]
        at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:533) [Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) [FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:329) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) [lh.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.IllegalArgumentException: The modid PigManure is not the same as it's lowercase version. Lowercasing will be enforced in 1.11
        at net.minecraftforge.fml.common.FMLModContainer.sanityCheckModId(FMLModContainer.java:146) ~[FMLModContainer.class:?]
        at net.minecraftforge.fml.common.FMLModContainer.<init>(FMLModContainer.java:128) ~[FMLModContainer.class:?]
        ... 16 more`

The server is able to start but the PigManure mod does not load nor function.

**Logs**
[fml-server-latest.txt](https://github.com/airbreather/pig-manure-mod/files/677486/fml-server-latest.txt)

**Versions**
PigManure: 1.0.2-mc1.11
Forge: 1.11-13.19.1.2199-universal
Minecraft: 1.11

**Comment by airbreather** [comment]
Great... I apparently tested everything with 2188 (edit: which I'm pretty dang confident was the "recommended" build when I looked), and then what does 2189 (the currently recommended build) go and change?

    Enable Enforcement of modid formatting. Must be lowercase and <= 64 characters

**Comment by airbreather** [comment]
MinecraftForge/MinecraftForge@7fe8c48

Apparently even "Recommended" builds aren't safe from intentional breaking changes.

Fixed by bdc0061
